"""Feishu file type constants."""

FILE_TYPE_MAP: dict[str, str] = {
    ".opus": "opus",
    ".mp3": "opus",
    ".wav": "opus",
    ".m4a": "opus",
    ".aac": "opus",
    ".flac": "opus",
    ".mp4": "mp4",
    ".mov": "mp4",
    ".avi": "mp4",
    ".mkv": "mp4",
    ".webm": "mp4",
    ".pdf": "pdf",
    ".doc": "doc",
    ".docx": "doc",
    ".xls": "xls",
    ".xlsx": "xls",
    ".ppt": "ppt",
    ".pptx": "ppt",
    ".stream": "stream",
    ".txt": "stream",
    ".csv": "stream",
    ".json": "stream",
    ".md": "stream",
    ".xml": "stream",
    ".html": "stream",
    ".css": "stream",
    ".js": "stream",
    ".ts": "stream",
    ".py": "stream",
    ".go": "stream",
    ".java": "stream",
    ".c": "stream",
    ".cpp": "stream",
    ".h": "stream",
    ".sh": "stream",
    ".yaml": "stream",
    ".yml": "stream",
    ".toml": "stream",
    ".ini": "stream",
    ".cfg": "stream",
    ".log": "stream",
    ".zip": "stream",
    ".tar": "stream",
    ".gz": "stream",
    ".rar": "stream",
    ".7z": "stream",
}

IMAGE_EXTENSIONS: set[str] = {
    ".jpg",
    ".jpeg",
    ".png",
    ".gif",
    ".bmp",
    ".webp",
    ".ico",
    ".svg",
    ".tiff",
    ".tif",
}

AUDIO_EXTENSIONS: set[str] = {
    ".opus",
    ".mp3",
    ".wav",
    ".m4a",
    ".aac",
    ".flac",
}

VIDEO_EXTENSIONS: set[str] = {
    ".mp4",
    ".mov",
    ".avi",
    ".mkv",
    ".webm",
}
