"""Direct API workers for non-blocking generation (no LLM needed).

Each worker calls the Google API directly, saves the output file, and updates
the PendingResults heap. These run as asyncio tasks in the background.
"""

from __future__ import annotations

import asyncio
import time
import wave
from pathlib import Path
from typing import TYPE_CHECKING, Any

from loguru import logger

if TYPE_CHECKING:
    from scorpion.adk.pending import PendingResults

_MEDIA_ROOT = Path.home() / ".scorpion" / "media"

# Audio constants (shared with tools.py)
_SAMPLE_RATE = 48000
_CHANNELS = 2
_SAMPLE_WIDTH = 2
_TTS_SAMPLE_RATE = 24000
_TTS_CHANNELS = 1
_TTS_SAMPLE_WIDTH = 2


def _ts() -> str:
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")


async def worker_generate_video(
    result_id: str,
    prompt: str,
    duration: int,
    aspect: str,
    resolution: str,
    api_key: str,
    pending: PendingResults,
) -> None:
    """Generate a video via Veo 3.1 and update the pending heap."""
    out_dir = _MEDIA_ROOT / "videos"
    out_dir.mkdir(parents=True, exist_ok=True)

    try:
        from google import genai
        from google.genai import types

        client = genai.Client(api_key=api_key)
        logger.info(
            "[Worker:video:{}] Starting Veo 3.1 — prompt={!r} duration={}s aspect={} res={}",
            result_id, prompt[:80], duration, aspect, resolution,
        )

        operation = client.models.generate_videos(
            model="veo-3.1-generate-preview",
            prompt=prompt,
            config=types.GenerateVideosConfig(
                aspect_ratio=aspect,
                duration_seconds=duration,
                resolution=resolution,
                number_of_videos=1,
            ),
        )

        def _poll():
            poll_count = 0
            while not operation.done:
                poll_count += 1
                logger.info(
                    "[Worker:video:{}] Poll #{} (~{}s elapsed)",
                    result_id, poll_count, poll_count * 10,
                )
                time.sleep(10)
                client.operations.get(operation)
            return operation

        op = await asyncio.get_event_loop().run_in_executor(None, _poll)

        if not op.response or not op.response.generated_videos:
            pending.fail(result_id, "No videos generated by Veo")
            return

        video = op.response.generated_videos[0]
        client.files.download(file=video.video)
        out_path = out_dir / f"video_{_ts()}.mp4"
        video.video.save(str(out_path))
        logger.info("[Worker:video:{}] Saved: {}", result_id, out_path)
        pending.complete(result_id, [str(out_path)])

    except asyncio.CancelledError:
        logger.info("[Worker:video:{}] Cancelled", result_id)
        pending.fail(result_id, "Cancelled by user")
        raise
    except Exception as e:
        error_msg = str(e)
        logger.error("[Worker:video:{}] Failed: {}", result_id, e)
        if "503" in error_msg or "Service Unavailable" in error_msg:
            pending.fail(result_id, "Video service temporarily unavailable (503)")
        else:
            pending.fail(result_id, error_msg)


async def worker_generate_image(
    result_id: str,
    prompt: str,
    model: str,
    aspect: str,
    count: int,
    api_key: str,
    pending: PendingResults,
) -> None:
    """Generate image(s) via Imagen/Gemini and update the pending heap."""
    out_dir = _MEDIA_ROOT / "images"
    out_dir.mkdir(parents=True, exist_ok=True)

    try:
        from google import genai
        from google.genai import types

        client = genai.Client(api_key=api_key)
        logger.info(
            "[Worker:image:{}] Starting — model={} prompt={!r}",
            result_id, model, prompt[:80],
        )

        if model == "gemini":
            response = client.models.generate_content(
                model="gemini-3.1-flash-image-preview",
                contents=prompt,
                config=types.GenerateContentConfig(
                    response_modalities=["TEXT", "IMAGE"],
                ),
            )
            paths: list[str] = []
            ts = _ts()
            idx = 0
            for part in response.candidates[0].content.parts:
                if part.inline_data and part.inline_data.mime_type.startswith("image/"):
                    ext = part.inline_data.mime_type.split("/")[-1]
                    if ext == "jpeg":
                        ext = "jpg"
                    suffix = f"_{idx}" if idx > 0 else ""
                    out_path = out_dir / f"image_{ts}{suffix}.{ext}"
                    out_path.write_bytes(part.inline_data.data)
                    paths.append(str(out_path))
                    idx += 1

            if paths:
                pending.complete(result_id, paths)
            else:
                pending.fail(result_id, "No images generated")
            return

        model_map = {
            "imagen4": "imagen-4.0-generate-001",
            "imagen4-fast": "imagen-4.0-fast-generate-001",
            "imagen4-ultra": "imagen-4.0-ultra-generate-001",
        }
        model_id = model_map.get(model, "imagen-4.0-generate-001")

        response = client.models.generate_images(
            model=model_id,
            prompt=prompt,
            config=types.GenerateImagesConfig(
                number_of_images=count,
                aspect_ratio=aspect,
                person_generation="allow_adult",
            ),
        )

        paths = []
        for i, img in enumerate(response.generated_images):
            suffix = f"_{i}" if count > 1 else ""
            out_path = out_dir / f"image_{_ts()}{suffix}.png"
            out_path.write_bytes(img.image.image_bytes)
            paths.append(str(out_path))

        if paths:
            logger.info("[Worker:image:{}] Generated {} image(s)", result_id, len(paths))
            pending.complete(result_id, paths)
        else:
            pending.fail(result_id, "No images generated")

    except asyncio.CancelledError:
        logger.info("[Worker:image:{}] Cancelled", result_id)
        pending.fail(result_id, "Cancelled by user")
        raise
    except Exception as e:
        logger.error("[Worker:image:{}] Failed: {}", result_id, e)
        pending.fail(result_id, str(e))


async def worker_generate_music(
    result_id: str,
    prompt: str,
    duration: int,
    bpm: int,
    api_key: str,
    pending: PendingResults,
) -> None:
    """Generate music via Lyria RealTime and update the pending heap."""
    out_dir = _MEDIA_ROOT / "music"
    out_dir.mkdir(parents=True, exist_ok=True)

    try:
        from google import genai
        from google.genai import types

        client = genai.Client(
            api_key=api_key,
            http_options={"api_version": "v1alpha"},
        )

        bytes_per_sec = _SAMPLE_RATE * _CHANNELS * _SAMPLE_WIDTH
        target_bytes = duration * bytes_per_sec

        logger.info("[Worker:music:{}] Starting — prompt={!r} {}s", result_id, prompt[:60], duration)
        audio_chunks: list[bytes] = []
        collected = 0

        async with client.aio.live.music.connect(model="models/lyria-realtime-exp") as session:
            await session.set_weighted_prompts(
                prompts=[types.WeightedPrompt(text=prompt, weight=1.0)]
            )

            config_kwargs: dict[str, Any] = dict(
                density=0.5, brightness=0.5, guidance=4.0, temperature=1.0,
            )
            if bpm:
                config_kwargs["bpm"] = bpm

            await session.set_music_generation_config(
                config=types.LiveMusicGenerationConfig(**config_kwargs)
            )
            await session.play()

            async for message in session.receive():
                try:
                    chunk = message.server_content.audio_chunks[0].data
                    if chunk:
                        audio_chunks.append(chunk)
                        collected += len(chunk)
                        if collected >= target_bytes:
                            await session.pause()
                            break
                except (AttributeError, IndexError):
                    continue

        if not audio_chunks:
            pending.fail(result_id, "No audio received from Lyria")
            return

        pcm_data = b"".join(audio_chunks)
        out_path = out_dir / f"music_{_ts()}.wav"
        with wave.open(str(out_path), "wb") as wf:
            wf.setnchannels(_CHANNELS)
            wf.setsampwidth(_SAMPLE_WIDTH)
            wf.setframerate(_SAMPLE_RATE)
            wf.writeframes(pcm_data)

        logger.info("[Worker:music:{}] Saved: {} ({}s)", result_id, out_path, collected // bytes_per_sec)
        pending.complete(result_id, [str(out_path)])

    except asyncio.CancelledError:
        logger.info("[Worker:music:{}] Cancelled", result_id)
        pending.fail(result_id, "Cancelled by user")
        raise
    except Exception as e:
        logger.error("[Worker:music:{}] Failed: {}", result_id, e)
        pending.fail(result_id, str(e))


async def worker_generate_speech(
    result_id: str,
    text: str,
    voice: str,
    api_key: str,
    pending: PendingResults,
) -> None:
    """Generate speech via Gemini TTS and update the pending heap."""
    from scorpion.config.schema import TTS_MODEL

    out_dir = _MEDIA_ROOT / "voicemessage"
    out_dir.mkdir(parents=True, exist_ok=True)

    try:
        from google import genai
        from google.genai import types

        client = genai.Client(api_key=api_key)
        logger.info("[Worker:speech:{}] Starting — voice={} text={!r}", result_id, voice, text[:60])

        response = client.models.generate_content(
            model=TTS_MODEL,
            contents=f"Say naturally: {text}",
            config=types.GenerateContentConfig(
                response_modalities=["AUDIO"],
                speech_config=types.SpeechConfig(
                    voice_config=types.VoiceConfig(
                        prebuilt_voice_config=types.PrebuiltVoiceConfig(voice_name=voice)
                    )
                ),
            ),
        )

        audio_data = None
        for part in response.candidates[0].content.parts:
            if part.inline_data and part.inline_data.mime_type.startswith("audio/"):
                audio_data = part.inline_data.data
                break

        if not audio_data:
            pending.fail(result_id, "No audio generated by TTS")
            return

        out_path = out_dir / f"speech_{_ts()}.wav"
        with wave.open(str(out_path), "wb") as wf:
            wf.setnchannels(_TTS_CHANNELS)
            wf.setsampwidth(_TTS_SAMPLE_WIDTH)
            wf.setframerate(_TTS_SAMPLE_RATE)
            wf.writeframes(audio_data)

        logger.info("[Worker:speech:{}] Saved: {} ({} bytes)", result_id, out_path, len(audio_data))
        pending.complete(result_id, [str(out_path)])

    except asyncio.CancelledError:
        logger.info("[Worker:speech:{}] Cancelled", result_id)
        pending.fail(result_id, "Cancelled by user")
        raise
    except Exception as e:
        logger.error("[Worker:speech:{}] Failed: {}", result_id, e)
        pending.fail(result_id, str(e))
