@echo off
echo Force rebuilding nanobot container...
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d
echo Attaching to logs...
docker-compose -f docker-compose.yml -f docker-compose.dev.yml logs -f
