"""Graph query keyword extraction.

Extracted from the former ``helpers.py`` — this logic belongs in the graph
subpackage since it serves graph entity lookup exclusively.
"""

from __future__ import annotations

import re

_GRAPH_QUERY_STOPWORDS: frozenset[str] = frozenset(
    {
        "the",
        "this",
        "that",
        "then",
        "than",
        "they",
        "them",
        "there",
        "these",
        "those",
        "what",
        "when",
        "where",
        "which",
        "while",
        "who",
        "whom",
        "whose",
        "why",
        "how",
        "also",
        "and",
        "but",
        "for",
        "from",
        "into",
        "just",
        "like",
        "not",
        "only",
        "some",
        "such",
        "very",
        "will",
        "with",
        "would",
        "could",
        "should",
        "about",
        "after",
        "before",
        "been",
        "being",
        "have",
        "here",
        "more",
        "most",
        "much",
        "over",
        "same",
        "still",
        "each",
        "even",
        "every",
        "other",
        "are",
        "was",
        "were",
        "had",
        "has",
        "does",
        "did",
        "any",
        "its",
        "can",
        "may",
        "is",
        "it",
        "an",
        "or",
        "no",
        "do",
        "so",
        "if",
        "my",
        "me",
        "his",
        "her",
        "our",
        "your",
        "their",
        "a",
        "of",
        "in",
        "on",
        "to",
        "at",
        "by",
        "currently",
        "involved",
        "caused",
        "resolved",
        "apply",
    }
)


def _extract_query_keywords(query: str) -> set[str]:
    """Extract significant keywords from a query for graph entity lookup."""
    tokens = {t for t in re.findall(r"[a-zA-Z0-9_\-]+", query.lower()) if len(t) > 2}
    return tokens - _GRAPH_QUERY_STOPWORDS
