#!/usr/bin/env bash
# Idempotently install/uninstall nanobot's host-side cron jobs.
#
# Usage:
#   scripts/install-cron.sh install    # install or refresh nanobot's cron block
#   scripts/install-cron.sh uninstall  # remove nanobot's cron block
#   scripts/install-cron.sh show       # show the current nanobot block
#   scripts/install-cron.sh diff       # show what would change vs current user crontab
#
# Idempotency strategy: a tagged block delimited by "# >>> nanobot >>>" and
# "# <<< nanobot <<<" lines. On (re-)install we strip any existing block then
# append a fresh one. Everything outside the block is preserved.
#
# Jobs installed:
#   - reminders-archive (Peewee): Sundays 04:00 BST, archives stale rows out of
#     memory/REMINDERS.md so the active file stays small. Skipped if the skill
#     is missing.
#
# Add new jobs by appending to the heredoc in nanobot_block_content() below.

set -euo pipefail

readonly BEGIN_MARKER='# >>> nanobot >>>'
readonly END_MARKER='# <<< nanobot <<<'

# ---- helpers ----------------------------------------------------------------

current_crontab() {
  # Suppress "no crontab for $USER" — that's fine, we'll create one.
  crontab -l 2>/dev/null || true
}

strip_existing_block() {
  # Read stdin, emit only lines outside the BEGIN/END markers.
  awk -v b="$BEGIN_MARKER" -v e="$END_MARKER" '
    $0 == b { in_block = 1; next }
    $0 == e { in_block = 0; next }
    !in_block
  '
}

nanobot_block_content() {
  # Compose the block from individual job sections. Each helper prints
  # zero or more "cron expression  command" lines. Add new jobs by writing
  # a new helper and calling it here.
  echo "$BEGIN_MARKER"
  echo "# Auto-generated by scripts/install-cron.sh — do not edit between markers."
  echo "# Re-run 'make install-cron' to refresh."
  job_reminders_archive
  echo "$END_MARKER"
}

job_reminders_archive() {
  local script="$HOME/.nanobot/workspace/skills/reminders/reminders-archive"
  local log="$HOME/.nanobot/workspace/skills/reminders/archive.log"
  if [[ ! -x "$script" ]]; then
    echo "# reminders-archive: SKIPPED — $script not found or not executable"
    return
  fi
  echo "# Peewee: archive stale rows from memory/REMINDERS.md every Sunday 04:00"
  echo "0 4 * * 0 $script >> $log 2>&1"
}

install_block() {
  local rest new
  rest="$(current_crontab | strip_existing_block)"
  new="$rest"$'\n'"$(nanobot_block_content)"
  # Drop any leading blank line and collapse runs of >2 blank lines.
  printf '%s\n' "$new" \
    | awk 'NR==1 && NF==0 {next} {print}' \
    | awk 'BEGIN{blank=0} /^$/{blank++; if(blank<=1) print; next} {blank=0; print}' \
    | crontab -
  echo "Installed nanobot cron block:"
  show_block
}

uninstall_block() {
  if ! current_crontab | grep -qF "$BEGIN_MARKER"; then
    echo "Nothing to uninstall — no nanobot block found in current crontab."
    return 0
  fi
  current_crontab | strip_existing_block | crontab -
  echo "Removed nanobot cron block."
}

show_block() {
  if ! current_crontab | grep -qF "$BEGIN_MARKER"; then
    echo "(no nanobot block installed)"
    return 0
  fi
  current_crontab | awk -v b="$BEGIN_MARKER" -v e="$END_MARKER" '
    $0 == b { in_block = 1 }
    in_block { print }
    $0 == e { in_block = 0 }
  '
}

diff_block() {
  local current new
  current="$(current_crontab)"
  new="$(printf '%s' "$current" | strip_existing_block)"$'\n'"$(nanobot_block_content)"
  if [[ -z "${current// }" ]]; then
    echo "(current crontab is empty)"
  fi
  diff -u <(printf '%s\n' "$current") <(printf '%s\n' "$new") || true
}

# ---- dispatch ---------------------------------------------------------------

cmd="${1:-install}"
case "$cmd" in
  install)   install_block ;;
  uninstall) uninstall_block ;;
  show)      show_block ;;
  diff)      diff_block ;;
  *)
    echo "Usage: $0 {install|uninstall|show|diff}" >&2
    exit 2
    ;;
esac
