"""Hermes-style self-evolution: traces, PostTask skill creation, GEPA updates."""

from nanobot.agent.evolution.deps import evolution_extra_available, require_evolution_extra
from nanobot.agent.evolution.gepa_optimizer import (
    GepaAutoBudget,
    GepaOptimizeResult,
    GepaOptimizer,
    GepaOptimizerConfig,
    build_trace_metric,
    examples_to_dspy,
    fast_trace_score,
    make_dspy_lm,
    resolve_gepa_optimizer_model,
    split_train_val,
)
from nanobot.agent.evolution.gepa_evaluator import (
    DEFAULT_MAX_CONCURRENCY,
    SKIP_BUDGET_EXCEEDED,
    GepaBatchEvalResult,
    GepaBudgetTracker,
    GepaEvalScore,
    GepaEvaluator,
    GepaEvaluatorConfig,
    composite_score,
    estimate_llm_cost_usd,
    format_tool_calls,
)
from nanobot.agent.evolution.gepa_dataset import (
    DEFAULT_MIN_TRACES,
    SKIP_INSUFFICIENT_TRACES,
    GepaDatasetResult,
    GepaEvalExample,
    build_gepa_dataset,
    trace_relates_to_skill,
)
from nanobot.agent.evolution.gepa_skill_module import (
    GepaSkillModule,
    GepaSkillState,
    SkillMdParts,
    extract_body_from_dspy_module,
    merge_skill_md,
    split_skill_md,
)
from nanobot.agent.evolution.gepa_status import (
    GEPA_SKIP_ALREADY_RUNNING,
    GepaRunLock,
    GepaRunPhase,
    GepaRunStatus,
    GepaRunStore,
    GepaRunTrigger,
)
from nanobot.agent.evolution.git_store import EvolutionGitStore
from nanobot.agent.evolution.models import ToolCallRecord, TurnTrace, TurnTraceOutcome
from nanobot.agent.evolution.post_task import (
    PostTaskCooldownStore,
    PostTaskDecision,
    PostTaskEvolver,
    PostTaskGateResult,
    parse_post_task_response,
    resolve_post_task_provider,
)
from nanobot.agent.evolution.proposals import (
    PostTaskCreateResult,
    ProposalActionResult,
    ProposalDetail,
    ProposalKind,
    ProposalMeta,
    ProposalStore,
    normalize_skill_md_content,
    validate_skill_md,
)
from nanobot.agent.evolution.trace_recorder import TraceRecorder, build_turn_trace
from nanobot.agent.evolution.trace_store import TraceStore

__all__ = [
    "DEFAULT_MAX_CONCURRENCY",
    "DEFAULT_MIN_TRACES",
    "EvolutionGitStore",
    "GEPA_SKIP_ALREADY_RUNNING",
    "GepaBatchEvalResult",
    "GepaBudgetTracker",
    "GepaDatasetResult",
    "GepaEvalExample",
    "GepaEvalScore",
    "GepaEvaluator",
    "GepaEvaluatorConfig",
    "GepaAutoBudget",
    "GepaOptimizeResult",
    "GepaOptimizer",
    "GepaOptimizerConfig",
    "GepaRunLock",
    "GepaSkillModule",
    "GepaSkillState",
    "GepaRunPhase",
    "GepaRunStatus",
    "GepaRunStore",
    "GepaRunTrigger",
    "PostTaskCooldownStore",
    "PostTaskCreateResult",
    "PostTaskDecision",
    "PostTaskEvolver",
    "PostTaskGateResult",
    "ProposalActionResult",
    "ProposalDetail",
    "ProposalKind",
    "ProposalMeta",
    "ProposalStore",
    "SKIP_BUDGET_EXCEEDED",
    "SKIP_INSUFFICIENT_TRACES",
    "SkillMdParts",
    "ToolCallRecord",
    "TraceRecorder",
    "TraceStore",
    "TurnTrace",
    "TurnTraceOutcome",
    "build_turn_trace",
    "build_gepa_dataset",
    "build_trace_metric",
    "composite_score",
    "examples_to_dspy",
    "fast_trace_score",
    "estimate_llm_cost_usd",
    "format_tool_calls",
    "evolution_extra_available",
    "extract_body_from_dspy_module",
    "make_dspy_lm",
    "merge_skill_md",
    "normalize_skill_md_content",
    "resolve_gepa_optimizer_model",
    "parse_post_task_response",
    "require_evolution_extra",
    "resolve_post_task_provider",
    "split_skill_md",
    "split_train_val",
    "trace_relates_to_skill",
    "validate_skill_md",
]
